# Created by: Roman Neuhauser <neuhauser@sigpipe.cz>
# $FreeBSD$

PORTNAME=	http-parser
PORTVERSION=	2.7.1
CATEGORIES=	devel
MASTER_SITES=	GITHUB

MAINTAINER=	neuhauser@sigpipe.cz
COMMENT=	HTTP request/response parser for C

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE-MIT

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	nodejs
GH_TAGNAME=	v${PORTVERSION}

ALL_TARGET=	library

.include <bsd.port.mk>
